name: Exercise Repository CI 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test default scheme using latest macos version
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v2
    
    - name: Build and Run Default Scheme
      run: xcodebuild clean build test -project ExerciseRepository/ExerciseRepository.xcodeproj -scheme "ExerciseRepository" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES

