name: Routine Repository CI 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test default scheme using latest macos version
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v2
    
    - name: Clean, Build, and Run CI_macOS Scheme
      run: xcodebuild clean build test -project RoutineRepository/RoutineRepository.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES
      
    - name: Clean, Build, and Run CI_iOS Scheme
       run: xcodebuild clean build test -project ExerciseRepository/ExerciseRepository.xcodeproj -scheme "CI_iOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 13 Pro Max" ONLY_ACTIVE_ARCH=YES | xcpretty

